title: Marshall's Github Page
description: > # this means to ignore newlines until "baseurl:"
  Coding gorgeously
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
# baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "https://marshallw906.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Marshall Wang # add your name
# author-img: R-Y.png # add your photo
author-img: MarshallWang.png # add your photo
about-author: Stay determined # add description
social-github: MarshallW906 # add your Github handle
social-linkedin: marshall-wang-256 # add your Linkedin handle
social-email: marshallw906@gmail.com # add your Email address

# Disqus
# discus-identifier: marshallw906 # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

timezone: "Asia/Shanghai"
encoding: utf-8

