title: Hello, world! I'm Marshall Wang
description: > # this means to ignore newlines until "baseurl:"
  Coding gorgeously
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
# baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "marshallw906.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Marshall Wang # add your name
author-img: R-Y.png # add your photo
about-author: I love Rina # add description
social-twitter: MarshallW906 # add your Twitter handle
social-facebook: marshallwang906 # add your Facebook handle
social-github: MarshallW906 # add your Github handle
social-linkedin: marshall-wang-256 # add your Linkedin handle
social-email: scareley@gmail.com # add your Email address

# Disqus
discus-identifier: marshallwang # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

timezone: "Asia/Shanghai"
encoding: utf-8

